services:
  frontend-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
