version: '3.8'

services:
  cart-db:
    image: mysql:8.4
    container_name: cart-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_cart
    ports:
      - "3307:3306"
    volumes:
      - ./db/cart_init.sql:/docker-entrypoint-initdb.d/init.sql
      - cart-db-data:/var/lib/mysql
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  cart-db-data:

networks:
  ecommerce-network:
    driver: bridge
