spring.application.name=cart-service

server.address=0.0.0.0
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3307/ecommerce_cart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mysecretkeymysecretkeymysecretkey12345

payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8083/api/payments/process}

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
