version: '3.8'

services:
  shipping-db:
    image: mysql:8.4
    container_name: shipping-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_shipping
    ports:
      - "3310:3306"
    volumes:
      - ./db/shipping_init.sql:/docker-entrypoint-initdb.d/init.sql
      - shipping-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  shipping-service:
    build: .
    container_name: shipping-service
    depends_on:
      shipping-db:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      PORT: 8085
      DB_HOST: shipping-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ecommerce_shipping

volumes:
  shipping-db-data:
